server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/FacundoSuarez/CloudConfig
  security:
    user:
      name: admin
      password: admin
